---
Name: lkdomains
After: 'framework/*'
---

# Database configuration
SilverStripe\ORM\Connect\MySQLDatabase:
  connection_charset: utf8mb4

# Enable full-text search
SilverStripe\ORM\DatabaseAdmin:
  require_default_records: true

---
Name: lkdomains-models
---

# Expose models to ORM
SilverStripe\ORM\DataObject:
  extensions:
    - LKDomains\Models\Members\Customer
    - LKDomains\Models\Organizations\Organization
    - LKDomains\Models\Members\OrganizationMember
    - LKDomains\Models\Registration\DomainReason
    - LKDomains\Models\Registration\Country
