---
Name: lkdomains
After: 'framework/*'
---

# Database configuration
SilverStripe\ORM\Connect\MySQLDatabase:
  connection_charset: utf8mb4

# Enable full-text search
SilverStripe\ORM\DatabaseAdmin:
  require_default_records: true
