version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - SS_ENVIRONMENT_TYPE=dev
    volumes:
      - .:/var/www/html
      - app_assets:/var/www/html/assets

volumes:
  app_assets:
